server:
  port: 8080

spring:
  application:
    name: archi-service

  profiles:
    active: local # ? ?? ??? ?? local / docker / prod (application-local.yml ? ?? ??? ?? ??)

  config:
    import: application-secret.yml # -> JWT ???, MySQL ???? ? ???? ??? ?? ??? import ??
